/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication5;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.WindowConstants;

/**
 *
 * @author Denis
 */
public class Agregar_Jugador extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Nodo_Jugador actual = null;
    L_Jugador lista = JavaApplication5.jugadores;

    public Agregar_Jugador() {
        //
        initComponents();
        

    }

    Agregar_Jugador(String Titulo) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        //this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setTitle(Titulo);
        L_Jugador aux = JavaApplication5.jugadores;
        if (aux.raiz != null) {
            //System.out.println("no es null");
            //System.out.println(this.getTitle());
            //System.out.println(aux.raiz.tipo);
            
            if (aux.raiz.tipo.equals(this.getTitle())) {
                //System.out.println("encontrado");
                actual = aux.raiz;
                this.txcant.setText(Integer.toString(actual.cantidad));
                this.txnombre.setText(actual.nombre);
            } else if (aux.raiz.siguiente != null) {
                actual = aux.raiz.siguiente;
            } else {
                this.txtext.setVisible(false);
                this.jLabel3.setVisible(false);
            }
        } else {
            this.txtext.setVisible(false);
            this.jLabel3.setVisible(false);
        }
         addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                JavaApplication5.prueba.setVisible(true);
                //e.getWindow().dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txnombre = new javax.swing.JTextField();
        txcant = new javax.swing.JTextField();
        txtext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txnombre.setToolTipText("");

        txcant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txcantActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Cantidad");

        jLabel3.setText("Texto");
        jLabel3.setToolTipText("");

        jButton1.setText("Agregar Mas Campos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txnombre)
                    .addComponent(txcant)
                    .addComponent(txtext))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txcantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txcantActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (actual == null) {
            if (this.txcant.getText().length() != 0 && this.txnombre.getText().length() != 0) {
                if (JavaApplication5.jugadores.raiz == null) {
                    JavaApplication5.jugadores.agregar_jugador(this.txnombre.getText(), Integer.parseInt(this.txcant.getText()), this.getTitle());
                    actual = JavaApplication5.jugadores.raiz;
                } else {
                    JavaApplication5.jugadores.agregar_jugador(this.txnombre.getText(), Integer.parseInt(this.txcant.getText()), this.getTitle());
                    actual = JavaApplication5.jugadores.raiz.siguiente;
                }
                this.jLabel3.setVisible(true);
                this.txtext.setVisible(true);
            }

        } else {
            
            actual.nombre = this.txnombre.getText();
            actual.cantidad = Integer.parseInt(this.txcant.getText());
            if (this.txtext.getText().length() != 0) {
                actual.agregar_texto(this.txtext.getText());
            }
            Nodo_Texto aux = actual.texto;
            while (aux != null) {
                //System.out.print(aux.texto+",");
                aux=aux.siguiente;
            }
            //System.out.println();
        }
        //L_Jugador aux=JavaApplication5.jugadores;
        //aux.agregar_jugador(this.txnombre.getText(),Integer.parseInt(this.txcant.getText()), this.getTitle());
        //System.out.println(this.getTitle());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txcant;
    private javax.swing.JTextField txnombre;
    private javax.swing.JTextField txtext;
    // End of variables declaration//GEN-END:variables
}
